export enum ErrorCode {
  // Generic codes
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Domain specific codes
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  QUEUE_FULL = 'QUEUE_FULL',
  TICKET_EXPIRED = 'TICKET_EXPIRED',

  // Auth / Tenant specific
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  FORBIDDEN_RESOURCE = 'FORBIDDEN_RESOURCE',
  TENANT_MISMATCH = 'TENANT_MISMATCH',
  ROLE_NOT_ASSIGNED = 'ROLE_NOT_ASSIGNED',
  STORE_NOT_FOUND = 'STORE_NOT_FOUND',
  ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',
}
